### ISSUE TITLE
I am expected to wait for the code release 😊

### ISSUE THREAD

**Issue by Mahiro2211** [lilujunai/Auto-Prox-AAAI24#1]

**Comment by Junaid199f** [comment]
Still Waiting

**Comment by lliai** [comment]
Thank you very much for your interest in our project! We appreciate your support. We have already released the code, and you can find it there. If you have any further questions or concerns, please feel free to reach out to us via email. We are more than happy to assist you and address any inquiries you may have. Thank you!
